/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gradlehelper.manifestToGradle;

import java.io.IOException;

import org.junit.Test;

public class AppTest {
    @Test
    public void testAppHasAGreeting() throws IOException {
        // ManifestConverter classUnderTest = new ManifestConverter();
        // assertEquals("Expect zero processed files", classUnderTest.start(), classUnderTest.getProcessedFiles());
    }
}
